kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: media-pvc
  namespace: qbittorrent-operator
spec:
  storageClassName: cinder
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
